### ISSUE TITLE
Refine and create a colour palette

### ISSUE THREAD

**Issue by o-y** [Bleu-Pigs/brand-guidelines#1]
The design and branding should be consistent across all platforms. Choose a palette which incorpreates various colours. Initial suggested colours:

Blues:
- Primary (BP Blue): #4169E0
- 500: #4299E1

Greys:
- 900: #1A202C
- 500: #A0AEC0
- 100: #F7FAFC

**Comment by ReinitiaIized** [comment]
Seems like a good start.

**Comment by o-y** [comment]
Moved to the Open Colour specification - https://yeun.github.io/open-color/

> NOTE, Generally the interfaces should exclusively use these colours:
- Teal 4: #38d9a9
- Orange 4: #ffa94d
- Cyan 5: #22b8cf
- Blue 4: #4dabf7
- Red 6: #ff6b6b
- Dark Grey (9): #212529
- Light Grey (7): #495057
- Near White (Grey 1): #f8f9fa
- The BP Blue should be used as a secondary colour for emphasising the brand - but no user interaction (#4169E0)
